#!/bin/bash

export GOOGLE_APPLICATION_CREDENTIALS=GCPCREDENTIALS
export WALG_GS_PREFIX=WALGGSPREFIX
export PGUSER=POSTGRESUSER
export PGDATABASE=POSTGRESDB
echo "GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS"
echo "WALG_GS_PREFIX: $WALG_GS_PREFIX"
echo "PGUSER: $PGUSER"
echo "PGDATABASE: $PGDATABASE"

/usr/local/bin/wal-g $1 $2
